"use client";

import { ArrowDown, ArrowRight } from "@phosphor-icons/react";
import Link from "next/link";
import { MirrorLens } from "@/components/mirror-lens";

const dimensions = ["Ownership — what you personally owned", "Scope — the size and boundaries of the work", "Impact — outcomes and supporting measures", "Consistency — whether the account holds across answers", "Role relevance — connection to the target role", "Communication — clarity under probing", "Evidence strength — what the session can support"];
const comparison = [["Questions", "Role-relevant and adaptive", "Generic or fixed"], ["Resume use", "Claims become traceable starting points", "Often treated as background"], ["Follow-ups", "Clarify ownership, scope, and measurement", "May stop at the first answer"], ["Output", "Evidence-backed diagnostic", "General feedback or a score"], ["Uncertainty", "Shown when signal is insufficient", "Often compressed away"]];

export function LandingStory() {
  return <main className="landing-page">
    <section className="landing-hero shell grid min-h-[calc(100dvh-4rem)] items-center gap-12 py-14 lg:grid-cols-[.94fr_1.06fr] lg:gap-20 lg:py-20">
      <div className="max-w-2xl"><p className="hero-eyebrow mb-7">Evidence-backed interview diagnostic</p><h1 className="hero-title display max-w-[11ch] text-5xl leading-[.93] font-semibold tracking-[-0.06em] sm:text-7xl lg:text-[5.35rem]">Know what your resume can defend.</h1><p className="hero-lede mt-8 max-w-[55ch] text-lg leading-8">Mirror maps your resume against a target role, then uses an adaptive interview to produce an evidence-backed readiness diagnostic.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="hero-primary-action">Start your diagnostic <ArrowRight size={18} /></Link><a href="#how-it-works" className="hero-secondary-action">See how it works <ArrowDown size={18} /></a></div><p className="hero-proof-line mono mt-7">Resume + target role + adaptive interview + evidence audit</p></div>
      <div className="relative flex min-h-[26rem] items-center justify-center border-y hairline py-8 lg:border-y-0 lg:border-l lg:py-0"><div className="hero-proof" aria-label="Illustrative evidence diagnostic example"><div className="hero-proof-topline"><span>Illustrative diagnostic</span><span>Evidence trace</span></div><div className="hero-proof-section"><p className="hero-proof-label">Claim</p><p className="hero-claim">Improved checkout conversion by 18%.</p></div><div className="hero-proof-arrow">↓</div><div className="hero-proof-section"><p className="hero-proof-label">Follow-up</p><p className="hero-followup">What part of the experiment did you personally own?</p></div><div className="hero-proof-arrow">↓</div><div className="hero-evidence-grid"><p className="hero-proof-label hero-evidence-heading">Evidence</p><dl><div><dt>Ownership</dt><dd>Direct</dd></div><div><dt>Metric support</dt><dd>Partial</dd></div><div><dt>Scope</dt><dd>Verified</dd></div><div><dt>Outcome evidence</dt><dd>Supported</dd></div></dl></div><div className="hero-diagnostic"><p className="hero-proof-label">Diagnostic</p><div><span>Role readiness</span><strong>72–80%</strong></div><div><span>Interview readiness</span><strong>64–73%</strong></div></div><MirrorLens /></div></div>
    </section>

    <section id="why" className="landing-section research-section"><div className="landing-shell research-grid"><div><p className="section-label">The problem</p><h2>The resume is still the entry point. But it is no longer enough.</h2></div><div className="research-signals"><article><h3>Skills need evidence</h3><p>Skills-based hiring shifts attention from titles alone toward demonstrated capability.</p><a href="https://economicgraph.linkedin.com/content/dam/me/economicgraph/en-us/PDF/skills-based-hiring-march-2025.pdf">LinkedIn Economic Graph, 2025</a></article><article><h3>Structure matters</h3><p>Job-relevant, structured interviews have stronger evidence than unstructured conversation.</p><a href="https://home.ubalt.edu/tmitch/645/articles/McDanieletal1994CriterionValidityInterviewsMeta.pdf">McDaniel et al., 1994</a></article><article><h3>Polish is not proof</h3><p>A polished application cannot by itself show ownership, scope, or the basis for an outcome.</p><span>Mirror product framing</span></article></div></div></section>

    <section id="how-it-works" className="landing-section"><div className="landing-shell"><p className="section-label">How Mirror works</p><h2 className="section-title">A connected trail from claim to diagnostic.</h2><ol className="method-flow"><li><b>01</b><strong>Resume</strong><span>Claims become starting points.</span></li><li><b>02</b><strong>Target role</strong><span>Requirements set the context.</span></li><li><b>03</b><strong>Adaptive interview</strong><span>Follow-ups seek useful detail.</span></li><li><b>04</b><strong>Evidence audit</strong><span>Support and uncertainty stay visible.</span></li><li><b>05</b><strong>Readiness diagnostic</strong><span>Findings become next actions.</span></li></ol></div></section>

    <section className="landing-section questioning-section"><div className="landing-shell two-column"><div><p className="section-label">A claim under questioning</p><h2>Precision arrives one question at a time.</h2><p className="section-copy">Mirror does not decide whether a person is truthful. It asks for enough context to understand what an answer can—and cannot—support.</p></div><div className="question-ledger"><p className="ledger-claim">“Improved checkout conversion by 18%.”</p>{["What did you personally own?", "How was the 18% calculated?", "What was the baseline?", "Who else contributed?"].map((question, index) => <div key={question}><span>0{index + 1}</span><p>{question}</p><em>{index === 0 ? "Supported" : index === 1 ? "Partial" : index === 2 ? "Not enough signal" : "Clarify"}</em></div>)}</div></div></section>

    <section className="landing-section"><div className="landing-shell two-column"><div><p className="section-label">What Mirror evaluates</p><h2>Not confidence. The evidence behind it.</h2></div><dl className="evaluation-ledger">{dimensions.map((dimension, index) => { const [name, detail] = dimension.split(" — "); return <div key={name}><dt>{String(index + 1).padStart(2, "0")}</dt><dd><strong>{name}</strong><span>{detail}</span></dd></div>; })}</dl></div></section>

    <section className="landing-section diagnostic-section"><div className="landing-shell"><p className="section-label">Illustrative diagnostic</p><div className="diagnostic-preview"><div><span>Role readiness</span><strong>72–80%</strong><small>Evidence supports several target-role claims.</small></div><div><span>Interview readiness</span><strong>64–73%</strong><small>Ownership and baseline need more precision.</small></div><div><span>Claims audit</span><b>1 supported · 1 partial · 1 needs signal</b></div><div><span>Recommended action</span><b>Practice explaining baseline, ownership, and scope.</b></div></div></div></section>

    <section className="landing-section"><div className="landing-shell"><p className="section-label">Not another generic mock interview</p><h2 className="section-title">A diagnostic has a different job.</h2><div className="comparison" role="table" aria-label="Mirror compared with a generic mock interview"><div role="row" className="comparison-head"><span>Approach</span><span>Mirror</span><span>Generic mock interview</span></div>{comparison.map(([label, mirror, generic]) => <div role="row" key={label}><strong>{label}</strong><span>{mirror}</span><span>{generic}</span></div>)}</div></div></section>

    <section className="landing-section trust-section"><div className="landing-shell trust-grid"><div><p className="section-label">Trust and limits</p><h2>Useful signal should remain accountable.</h2></div><ul><li>No live performance score during the interview.</li><li>Findings point to evidence from the session.</li><li>Not enough signal is a valid outcome.</li><li>Candidate-facing reports do not show hidden reasoning.</li><li>Mirror is a diagnostic, not a hiring authority.</li></ul></div></section>

    <section className="landing-section final-cta"><div className="landing-shell"><p className="section-label">Start with the evidence</p><h2>Know what holds before the interview asks.</h2><div><Link href="/signup" className="hero-primary-action">Start your diagnostic <ArrowRight size={18} /></Link><a href="#how-it-works" className="hero-secondary-action">See how it works <ArrowDown size={18} /></a></div></div></section>
    <footer className="landing-footer"><div className="landing-shell"><p>Mirror evaluates evidence from this session. AI can make mistakes. Outcome validation is still in progress.</p><p>by Pathwisse</p></div></footer>
  </main>;
}
