"""Voice latency harness.

Runs the real voice turn pipeline (Supabase, Sarvam STT/TTS, the interviewer model)
against a throwaway clone of a prepared session, then prints p50/p95 per stage.

    python scripts/voice_latency_harness.py --label baseline --turns 30
    python scripts/voice_latency_harness.py --label fix1 --turns 30 --flags VOICE_HTTP_POOL=true,VOICE_PARALLEL_CONTEXT=true

Audio: WAV/MP3 files in tests/fixtures/audio are used when present (drop real recordings
there). Otherwise short synthetic answers are generated once with the TTS provider; those
measure latency only, not accuracy. The clone is marked synthetic and deleted afterwards.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import statistics
import sys
import time
from pathlib import Path
from uuid import UUID, uuid4

ROOT = Path(__file__).resolve().parents[1]
AUDIO_DIR = ROOT / "tests" / "fixtures" / "audio"
SOURCE_SESSION = "ec47fb89-ebae-4a48-9660-e51e1db8905e"
ANSWERS = [
    "I worked on a checkout project where I analysed drop off data and suggested changes to the payment page.",
    "My part was building the dashboard in Tableau and presenting the weekly numbers to my team.",
    "We compared two versions of the page and the new one improved conversion by a small margin.",
    "I learned that clear communication with the team matters as much as the analysis itself.",
    "I would start by checking the data quality and then talk to the people who use the report.",
]
STAGES = ["stt_ms", "context_build_ms", "interviewer_ms", "tts_ms", "storage_ms", "total_turn_ms"]


def pct(values: list[float], p: float) -> float:
    ordered = sorted(values)
    return ordered[min(len(ordered) - 1, int(len(ordered) * p))]


async def load_samples(tts, language: str) -> list[tuple[bytes, str]]:
    files = sorted([*AUDIO_DIR.glob("*.wav"), *AUDIO_DIR.glob("*.mp3")])
    if not files:
        AUDIO_DIR.mkdir(parents=True, exist_ok=True)
        for index, text in enumerate(ANSWERS):
            result = await tts.synthesize(text, language)
            (AUDIO_DIR / f"synthetic_{index}.mp3").write_bytes(result.audio_bytes)
        (AUDIO_DIR / "README.md").write_text(
            "synthetic_*.mp3 are generated by the TTS provider for latency tests only (not accuracy).\n"
            "Drop real recordings (.wav/.mp3) here and the harness will use them instead.\n",
            encoding="utf-8",
        )
        files = sorted(AUDIO_DIR.glob("*.mp3"))
    return [(f.read_bytes(), "audio/wav" if f.suffix == ".wav" else "audio/mpeg") for f in files]


def rest(settings):
    import httpx

    headers = {
        "apikey": settings.supabase_service_role_key,
        "Authorization": f"Bearer {settings.supabase_service_role_key}",
        "Prefer": "return=representation",
    }
    base = settings.next_public_supabase_url.rstrip("/") + "/rest/v1/"
    return httpx.Client(headers=headers, base_url=base, timeout=30)


def clone_session(db) -> tuple[UUID, UUID]:
    session = db.get("sessions", params={"id": f"eq.{SOURCE_SESSION}", "select": "*"}).json()[0]
    plan = db.get("interview_plans", params={"session_id": f"eq.{SOURCE_SESSION}", "select": "*"}).json()[0]
    new_id = str(uuid4())
    session.update(
        id=new_id, status="READY", phase="INTRO", started_at=None, completed_at=None, synthetic=True,
        elapsed_seconds=0, current_probe_count=0, total_questions=0, recovery_count=0,
        current_primary_question_id=None, completion_pct=0, phase_started_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    )
    created = db.post("sessions", json=session)
    created.raise_for_status()
    plan.update(id=str(uuid4()), session_id=new_id)
    db.post("interview_plans", json=plan).raise_for_status()
    return UUID(new_id), UUID(session["user_id"])


def cleanup(db, session_id: UUID) -> None:
    for table in ("voice_turn_metrics", "voice_turn_requests", "turns", "session_events", "interview_plans", "sessions"):
        key = "id" if table == "sessions" else "session_id"
        db.delete(table, params={key: f"eq.{session_id}"})


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--label", default="run")
    parser.add_argument("--turns", type=int, default=30)
    parser.add_argument("--pause", type=float, default=0.0, help="seconds between turns (a person speaks between turns; 0 stresses provider rate limits)")
    parser.add_argument("--flags", default="", help="comma list, e.g. VOICE_HTTP_POOL=true")
    args = parser.parse_args()
    for item in filter(None, args.flags.split(",")):
        key, _, value = item.partition("=")
        os.environ[key] = value
    sys.path.insert(0, str(ROOT / "apps" / "api"))

    from app.config import get_settings
    from app.dependencies import get_text_to_speech_provider, get_voice_interview_service
    from app.interview_engine import InterviewFlowRejected

    settings = get_settings()
    service = get_voice_interview_service()
    samples = await load_samples(get_text_to_speech_provider(), settings.interview_tts_language)
    db = rest(settings)

    import collections
    import httpx

    calls: collections.Counter[str] = collections.Counter()
    original_send = httpx.AsyncClient.send

    async def counting_send(self, request, **kwargs):
        host = request.url.host
        if "supabase" in host:
            calls[f"{request.method} {request.url.path.split('/v1/')[-1].split('?')[0][:40]}"] += 1
        return await original_send(self, request, **kwargs)

    httpx.AsyncClient.send = counting_send  # type: ignore[method-assign]
    walls: list[float] = []
    session_ids: list[UUID] = []
    done = 0
    failures = 0
    try:
        while done < args.turns:
            session_id, user_id = clone_session(db)
            session_ids.append(session_id)
            await service.start(session_id, user_id)
            while done < args.turns:
                audio, mime = samples[done % len(samples)]
                if done and args.pause:
                    await asyncio.sleep(args.pause)
                started = time.perf_counter()
                try:
                    await service.submit(
                        session_id, user_id, content=audio, claimed_mime_type=mime,
                        client_turn_id=uuid4(), recorded_duration_ms=4000, audio_upload_ms=0,
                    )
                except InterviewFlowRejected:
                    break  # this clone finished; start another
                except Exception as exc:  # noqa: BLE001 - the harness reports and continues
                    failures += 1
                    print(f"turn {done + 1}: {type(exc).__name__}")
                    done += 1
                    continue
                walls.append((time.perf_counter() - started) * 1000)
                done += 1
                print(f"turn {done}: {walls[-1]:.0f} ms", flush=True)
        from app.deferred_writes import get_deferred_writes

        await get_deferred_writes().flush_all()
        rows = []
        for sid in session_ids:
            rows += db.get("voice_turn_metrics", params={"session_id": f"eq.{sid}", "select": "*", "stt_ms": "gt.0"}).json()
        print(f"\n== {args.label}: flags={args.flags or 'none'} turns={len(walls)} failures={failures}")
        print(f"{'wall (client)':18s} p50={pct(walls, .5):7.0f}  p95={pct(walls, .95):7.0f}  ms")
        for stage in STAGES:
            values = [row[stage] for row in rows if row.get(stage) is not None]
            if values:
                print(f"{stage:18s} p50={pct(values, .5):7.0f}  p95={pct(values, .95):7.0f}  ms (n={len(values)})")
        print(f"mean wall {statistics.mean(walls):.0f} ms")
        total = sum(calls.values())
        print(f"supabase calls: {total} total, {total / max(1, len(walls)):.1f} per turn (includes clone/setup)")
        for name, count in calls.most_common(14):
            print(f"   {count / max(1, len(walls)):5.1f}/turn  {name}")
    finally:
        for sid in session_ids:
            cleanup(db, sid)
        print("cleaned up", len(session_ids), "synthetic session(s)")


if __name__ == "__main__":
    asyncio.run(main())
