/** Words for onboarding and adding a role (see docs/copy-guide.md). */
import type { EvidenceKind } from "@/lib/api-evidence";

export const onboardingCopy = {
  progress: {
    label: (step: number, total: number) => `Step ${step} of ${total}`,
    saved: "Your progress saves as you go. You can leave and pick up here later.",
    restoring: "Bringing back your saved progress.",
    steps: ["Your role", "Your experience", "Your examples", "Your plan"],
  },
  role: {
    title: "What role are you preparing for?",
    intro: "Tell us the role. If you have the job description, add it so your plan fits this opportunity.",
    targetSetupError: "Your role details are saved, but company setup didn't finish. Retry company setup, or continue with your general role plan. Without a target, your plan won't include company-specific interview rounds.",
    retryTarget: "Retry company setup",
    continueWithoutTarget: "Continue with general role plan",
    targetReady: "Company interview target is ready.",
    roleLabel: "Role",
    rolePlaceholder: "Product Manager",
    orgLabel: "Organisation",
    optional: "Optional",
    orgPlaceholder: "Organisation name",
    briefTitle: "Job description",
    briefIntro: "Choose any option. Each one works.",
    upload: "Upload it",
    paste: "Paste it",
    skip: "Skip for now",
    pasteLabel: "Job description text",
    pastePlaceholder: "Paste the responsibilities and what the role asks for.",
    uploaded: "Job description added",
    uploading: (percent: number) => percent < 100 ? `Uploading your job description, ${percent}%` : "Upload complete. Reading the text.",
    uploadProgress: "Job description upload",
    continue: "Continue",
    working: "Getting to know the role",
    workingNote: "This usually takes a few seconds. Your choices are locked until it finishes.",
    chooseBrief: "Choose upload, paste or skip for the job description.",
    pasteEmpty: "Paste the job description, or choose skip for now.",
    roleNotReady: "We couldn't finish getting to know the role just now. Please try again in a moment.",
  },
  experience: {
    title: "Bring in the work you want to talk about.",
    intro: "Your resume is the starting point. You'll see what we picked out and can change any of it.",
    savedLabel: "Your saved resume",
    useSaved: "Use my saved experience",
    replace: "Upload a different resume",
    upload: "Upload my resume",
    fileHint: (megabytes: number) => `PDF or DOCX, up to ${megabytes} MB`,
    uploading: (percent: number) => percent < 100 ? `Uploading your resume, ${percent}%` : "Upload complete. Saving it to your experience.",
    uploadProgress: "Resume upload",
    reading: "Reading your resume",
    readingNote: "This can take up to a minute. You can leave and come back; nothing is lost.",
    back: "Back",
  },
  review: {
    title: "Here is what I found. Is this right?",
    intro: "Keep what is true, fix what is not quite right, and remove anything you don't want to use. Only what you keep goes into your plan.",
    groups: {
      ACHIEVEMENT: "Your achievements",
      PROJECT: "Your projects",
      RESPONSIBILITY: "What you were responsible for",
      SKILL: "Your skills",
    } satisfies Record<EvidenceKind, string>,
    outcome: "Outcome",
    metric: "Result in numbers",
    detail: "Detail",
    titleField: "What you did",
    edit: "Edit",
    remove: "Remove",
    keep: "Keep this",
    kept: "Kept",
    edited: "Edited by you",
    removed: "Removed.",
    restore: "Bring it back",
    save: "Save changes",
    cancel: "Cancel",
    useInPlan: "Use this in my plan",
    saving: "Saving",
    readingTitle: "Reading your resume",
    readingBody: "This can take up to a minute. We'll show what we found as soon as it's ready.",
    unreadableTitle: "We couldn't read this resume.",
    unreadableBody: "A text-based PDF or DOCX usually works best. You can upload another one, or carry on and add examples later in My experience.",
    reupload: "Upload another resume",
    continueAnyway: "Continue without it",
    noResumeTitle: "We don't have your resume yet.",
    noResumeBody: "Add your resume so your plan can start from your own work.",
    addResume: "Add my resume",
    unavailableTitle: "Your examples will appear here shortly.",
    unavailableBody: "You can carry on now and review them later in My experience.",
    continue: "Continue",
    emptyTitle: "We didn't find clear examples in this resume.",
    emptyBody: "You can carry on and add examples later in My experience.",
    saveError: "We couldn't save that change just now. Your other changes are kept. Please try again.",
    loadError: "We couldn't load what we found just now. Your resume is saved. Please try again.",
    retry: "Try again",
    back: "Back",
  },
  plan: {
    title: (role: string) => `Your ${role} preparation plan is ready.`,
    intro: "Three areas to focus on first, and the examples from your experience that support them.",
    areasTitle: "Where to focus first",
    examplesTitle: "Your strongest examples",
    noExamples: "Once you keep a few examples, they will show up here and in your plan.",
    firstTitle: "Recommended first step",
    first: (area: string) => `A 5-minute practice on ${area.toLocaleLowerCase()}. One question, a short reflection after.`,
    firstFallback: "A 5-minute practice on one role question. One question, a short reflection after.",
    seePlan: "See your plan",
    startInstead: "Start a short practice instead",
    exitsNote: "Nothing starts until you choose. Your plan is saved either way.",
    loading: "Putting your plan together.",
    loadError: "We couldn't load your plan just now. Your role and examples are saved.",
    retry: "Try again",
    finishError: "We couldn't save that just now. Please check your connection and try again.",
    opening: "Opening",
  },
  newRole: {
    eyebrow: "Add a role",
    activeNote: "This is now your active role. You can switch roles at any time.",
  },
  errors: {
    save: "We couldn't save this part just now. Please check your connection and try again.",
    restore: "We couldn't bring back everything you saved just now. Please refresh to try again.",
  },
} as const;
