/**
 * Central copy for Mirror. Tone rules and glossary: docs/copy-guide.md.
 * Everything here is shown to people, so it is linted for banned words
 * (scripts/copy_lint.py). Keep identifiers and API field names out of it.
 */

export const meta = {
  title: "Mirror by Pathwisse",
  description:
    "A calm space to practice talking about your experience, with a friendly voice conversation and a kind, clear reflection afterward.",
  skipLink: "Skip to content",
  byline: "by Pathwisse",
} as const;

export const landing = {
  hero: {
    eyebrow: "A calm space to practice",
    title: "Find the words for your experience.",
    subline:
      "Mirror reads your resume and your target role, then has a relaxed voice conversation with you. Afterward, you get a gentle reflection on what came through clearly and what to practice next.",
    primaryCta: "Start practicing",
    secondaryCta: "See a sample reflection",
    underButtons: "Your resume · Your target role · A friendly conversation · A kind reflection",
  },
  heroCard: {
    ariaLabel: "A sample reflection",
    label: "A sample reflection",
    storyLabel: "Your story",
    story: "“Improved checkout conversion by 18%.”",
    followUpLabel: "A follow-up you might hear",
    followUp: "What part of the experiment did you lead yourself?",
    cameThroughLabel: "What came through",
    cameThrough: [
      ["Your role", "Clearly"],
      ["The numbers behind it", "Mostly"],
      ["Scope", "Clearly"],
      ["Results", "Clearly"],
    ],
    readinessLabel: "Readiness",
    roleReadiness: "Role readiness",
    interviewReadiness: "Interview readiness",
    roleRange: "72–80%",
    interviewRange: "64–73%",
  },
  problem: {
    eyebrow: "Why practice",
    title: "Your resume opens the door. Your words carry you through.",
    body: "Every interview starts with a resume. But in the room, people remember how you explain what you did: what was yours, how you knew it worked, and what you learned. That's a skill, and it gets easier with practice.",
    cards: [
      {
        title: "Skills speak through stories",
        body: "Hiring is moving from job titles toward what people can actually do.",
        source: "LinkedIn Economic Graph, 2025",
        href: "https://economicgraph.linkedin.com/content/dam/me/economicgraph/en-us/PDF/skills-based-hiring-march-2025.pdf",
      },
      {
        title: "Structure helps",
        body: "Interviews built around the role tend to be more reliable than open-ended chats.",
        source: "McDaniel et al., 1994",
        href: "https://home.ubalt.edu/tmitch/645/articles/McDanieletal1994CriterionValidityInterviewsMeta.pdf",
      },
      {
        title: "Polish is a start",
        body: "A well-written resume can't yet show what was yours, how big the work was, or how you knew it worked. Talking it through can.",
        source: "Mirror product framing",
        href: null,
      },
    ],
  },
  how: {
    eyebrow: "How Mirror works",
    title: "One gentle step at a time.",
    steps: [
      { n: "01", title: "Your resume", body: "Your experience becomes our starting point." },
      { n: "02", title: "Your target role", body: "The role sets the context." },
      { n: "03", title: "A friendly conversation", body: "Follow-up questions help you find the details." },
      { n: "04", title: "What came through", body: "What's clear and what's still forming both stay visible." },
      { n: "05", title: "Your reflection", body: "Everything turns into a small next step." },
    ],
  },
  moment: {
    eyebrow: "Details, one question at a time",
    title: "Your story, a little more clearly each time.",
    body: "Mirror isn't here to decide whether you're truthful. It asks for a little more context so your story comes across the way you mean it.",
    story: "“Improved checkout conversion by 18%.”",
    questions: [
      "What was yours to lead?",
      "How did you arrive at 18%?",
      "What were you comparing against?",
      "Who else helped?",
    ],
  },
  looksAt: {
    eyebrow: "What Mirror looks at",
    title: "Not how confident you sound. How clearly your story comes through.",
    items: [
      "What you led yourself",
      "The size and edges of the work",
      "Results and how you measured them",
      "Whether your story stays consistent",
      "How it connects to the role",
      "How clearly you explain when asked more",
      "How much this conversation can speak to",
    ],
  },
  sample: {
    eyebrow: "A sample reflection",
    roleReadiness: "Role readiness",
    roleRange: "72–80%",
    roleNote: "Several parts of your experience line up well with this role.",
    interviewReadiness: "Interview readiness",
    interviewRange: "64–73%",
    interviewNote: "Your starting point and role could be a little clearer.",
    cameThroughLabel: "What came through",
    cameThrough: "1 clearly · 1 mostly · 1 not explored yet",
    nextLabel: "Next step",
    next: "Practice describing where you started, what you led, and how big the work was.",
  },
  comparison: {
    eyebrow: "Not another generic mock interview",
    title: "More than a generic mock interview.",
    ariaLabel: "Mirror compared with a generic mock interview",
    head: ["Approach", "Mirror", "A generic mock interview"],
    rows: [
      ["Approach", "Built around your resume and role", "The same questions for everyone"],
      ["Your resume", "Becomes the starting point", "Often left in the background"],
      [
        "Follow-ups",
        "Gently explore your role, scope, and measures",
        "May move on after the first answer",
      ],
      ["Feedback", "A kind, clear reflection with next steps", "General tips or a number"],
      ["When it's unsure", "Says “not enough to say yet”", "Often guesses"],
    ],
  },
  trust: {
    eyebrow: "Trust and limits",
    title: "Kind, and honest about its limits.",
    points: [
      "No live ratings during your conversation.",
      "Every point in your reflection links back to a moment from your session.",
      "“Not enough to say yet” is a perfectly good outcome.",
      "Mirror is a practice partner, not a hiring decision-maker.",
      "Your resume and conversations stay private, and are not intentionally used to train third-party models.",
    ],
  },
  final: {
    eyebrow: "Start where you are",
    title: "Walk into your next interview knowing your own story.",
    cta: "Start practicing",
  },
  footer:
    "Mirror reflects on what came up in this session. AI can make mistakes, and we're still learning how well these reflections match real interview outcomes.",
} as const;

export const report = {
  title: (role: string) => `Your reflection · ${role}`,
  backToSpace: "Your space",
  navLabel: "Reflection navigation",
  loadingLabel: "Loading your reflection",
  summary: { eyebrow: "Your summary", levelToday: "Your level today" },
  shorterNote:
    "From a shorter conversation, so a few areas say “not enough to say yet.”",
  scope: {
    eyebrow: "This practice round",
    body: "This feedback covers this round only; it is not an overall role-readiness result.",
    provenance: "Mirror-generated practice rubric—not an official employer rubric.",
    competencies: (titles: string[]) => titles.length
      ? `This round looks at ${titles.join(" · ")}.`
      : "This round's focus is not available yet.",
  },
  readiness: {
    eyebrow: "Readiness",
    title: "Two signals, kept separate.",
    role: "Role readiness",
    interview: "Interview readiness",
    none: "Not enough to say yet",
    caption:
      "These appear as ranges because one conversation can only show so much.",
  },
  signal: {
    STRONG: "A clear picture",
    MODERATE: "A partial picture",
    WEAK: "A small picture",
    NONE: "Not enough to say yet",
  } as Record<string, string>,
  cameThrough: {
    eyebrow: "What came through",
    title: "What you shared, and how it came through",
    intro: "This is a gentle look at your own words. It starts with what came through clearly.",
    source: "Where it came from",
    note: "A short note",
    empty: "There wasn't anything to show here for this conversation.",
    noQuotes: "No matching moments were captured for this one.",
    sourceDocument: "Your resume or documents",
    interviewTurn: "Your conversation",
    groups: {
      held: "Came through clearly",
      partially_held: "Mostly came through",
      walked_back: "Refined during the conversation",
      contradicted: "Worth revisiting",
      insufficient_evidence: "Not enough to say yet",
      unverified: "Not yet explored",
    },
  },
  skills: {
    eyebrow: "Your skills",
    title: "How each skill came through",
    clear: "Came through clearly",
    mostly: "Mostly came through",
    none: "Not enough to say yet",
    empty: "Notes on each skill will appear here when they're ready.",
  },
  moments: {
    eyebrow: "Moments from your session",
    title: "Moments worth remembering",
    empty: "No time-linked moments were recorded.",
    labels: {
      STRONG_EVIDENCE: "Came through strongly",
      RECOVERY: "Found your footing",
      OWNERSHIP_CLARIFICATION: "Your role became clearer",
      UNSUPPORTED_SCALE: "A number worth explaining",
      TECHNICAL_DEPTH: "Technical depth",
    } as Record<string, string>,
  },
  growth: {
    eyebrow: "Your main growth area",
    intro:
      "Mirror picked one area from this conversation as a starting point, so your next practice session has a clear direction.",
    exerciseLabel: "A tiny exercise to try",
    areas: {
      OWNERSHIP_SPECIFICITY: {
        name: "Describing what you led",
        exercise: "Pick one project and say, in two sentences, what you did yourself and what your team did.",
      },
      TECHNICAL_DEPTH: {
        name: "Going a little deeper on how it works",
        exercise: "Choose one topic and explain it out loud, as if to a friend. Include one choice you made and why.",
      },
      ANSWER_STRUCTURE: {
        name: "Shaping your answers",
        exercise: "Try answering in three short parts: the situation, what you did, and what happened.",
      },
      OUTCOME_EVIDENCE: {
        name: "Explaining your results",
        exercise: "Take one number from your resume. Say where it started, what changed, and how you knew.",
      },
      COMPOSURE_UNDER_PROBE: {
        name: "Staying comfortable when asked more",
        exercise: "Before you answer a follow-up, take two slow breaths. A pause is always welcome.",
      },
      ROLE_SKILL_GAP: {
        name: "Building skills for this role",
        exercise: "Choose one skill from the job description, and write down one small way to practice it this week.",
      },
    } as Record<string, { name: string; exercise: string }>,
    fallback: {
      name: "One area to explore",
      exercise: "Pick one moment from your session and tell it again, a little more slowly.",
    },
  },
  plan: {
    eyebrow: "A small plan for this week",
    title: "Three small steps",
    steps: [
      "Try the tiny exercise above once, out loud.",
      "Pick one moment from your session and tell it again in your own words.",
      "Come back for another practice session whenever you feel ready.",
    ],
  },
  trust: {
    title: "What this reflection means, and what it doesn't",
    points: [
      "This reflects this one conversation.",
      "AI can make mistakes. If something doesn't sound right, you're welcome to tell us.",
      "Anything that didn't come up is never guessed.",
      "This is a practice reflection, not a hiring decision.",
    ],
    outcomeNotValidated: "We're still learning how well these reflections match real interview outcomes.",
    outcomeOther: "Outcome check:",
  },
  closing: {
    eyebrow: "A closing note",
    body: "Talking about your own work takes real effort, and you gave this your time. Thank you for that. Whenever you're ready, another conversation will be here.",
  },
  completed: "Completed",
  states: {
    processingTitle: "Reflecting on your answers",
    processingBody: "Mirror is looking at what you shared and how it connects to the role. Thank you for your patience.",
    returnToSpace: "Return to your space",
    failedTitle: "We couldn't finish your reflection just now",
    unavailableTitle: "Your reflection isn't available right now",
    savedRetry:
      "Your interview has been saved. Mirror couldn't finish reflecting on your answers, so it can be tried again without repeating the conversation.",
    longWait: "Your reflection is taking a little longer than expected. Please check back shortly.",
    notFound: "We couldn't find that reflection.",
    loadFailed: "We couldn't load your reflection just now. Please check your connection and try again.",
    retryFailed: "We couldn't try that again just now. Please try again in a moment.",
    retry: "Try again",
    retrying: "Trying again…",
  },
} as const;

export const voiceRoom = {
  doneAnswering: "I'm done answering",
  stepAway: {
    button: "Step away",
    title: "Need to step away?",
    body: "Your conversation is saved up to here. You can pick it back up whenever you like.",
    save: "Save and continue later",
    saving: "Saving your place…",
    end: "End and get my reflection",
    stay: "Stay in the conversation",
    saveFailed: "We couldn't save your place just now. Please try again.",
  },
  endConfirm: {
    body: "End here and get your reflection? It will be based on what we've talked about so far, so it may say \u201cnot enough to say yet\u201d in a few places.",
    confirm: "End and get my reflection",
    cancel: "Not yet",
  },
  draft: {
    title: "Your conversation is saved",
    copy: "Pick up where you left off.",
    continue: "Continue conversation",
    end: "End and get my reflection",
    ending: "Ending…",
  },
} as const;

/** Words and notes for the loading screens (see components/loader.tsx). */
export const loading = {
  app: { label: "Loading", note: "Just a moment." },
  signIn: { label: "Loading", note: "Opening sign in." },
  signUp: { label: "Loading", note: "Opening sign up." },
  onboarding: { label: "Getting ready", note: "Bringing back where you left off." },
  space: { label: "Loading", note: "Getting your space ready." },
  report: { label: "Loading", note: "Opening your reflection." },
  reflecting: { label: "Reflecting", note: "Looking at what you shared. Thank you for your patience." },
  room: { label: "Getting ready", note: "Preparing your room." },
} as const;

/** Home page (dashboard). "Review" is the candidate-facing word for what the report holds. */
export const home = {
  inProgress: { cont: "Continue practice" },
  beginReady: { begin: "Start practice" },
  recent: { previous: "Previous session" },
} as const;

/** Practice: where people start, continue and revisit their interview practice. */
export const practice = {
  eyebrow: "Practice",
  title: "Your practice",
  intro: "Short, repeatable practice on what matters for your role, or a full interview when you're ready.",
  start: "Start practice",
  recommendedTitle: "Recommended for you",
  recommendedFallback: "Choose something you'd like to practise.",
  startDrill: "Start",
  modesTitle: "Ways to practise",
  choose: "Choose",
  continueTitle: "Continue where you left off",
  lastPractised: (day: string) => `Last practised ${day}`,
  neverPractised: "Not practised yet",
  recommended: "Recommended",
  previousTitle: "Previous practice",
  previousEmpty: "Your finished practice will appear here.",
  historyLabel: "Previous practice",
  empty: {
    title: "You haven't practised yet.",
    body: "Choose a role and have your first conversation whenever you feel ready.",
    action: "Start practice",
  },
  errors: {
    load: "We couldn't load your practice just now. Nothing you've done has been removed.",
    retry: "Try again",
  },
} as const;

/** Starting a practice: which role, then how and what to practise. */
export const startPractice = {
  eyebrow: "Start practice",
  back: "Back",
  stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
  roleStep: {
    title: "What are you preparing for?",
    body: "Choose one of your roles, or add a new one.",
    another: "Prepare for another role",
    anotherBody: "Add a role and a job description.",
    empty: "You haven't added a role yet.",
    setupNeeded: "A little setup is needed",
    ready: "Ready to practise",
  },
  focusStep: {
    title: "What would you like to work on?",
    body: "Choose how long, then what to focus on.",
    howLabel: "How would you like to practise?",
    whatLabel: "What would you like to work on?",
    begin: "Start practice",
    preparing: "Preparing your practice…",
    failed: "We couldn't prepare that practice just now. You can try again without losing anything.",
  },
  story: {
    label: "The story you're practising",
    body: "Mirror asks about this story as you last saved it. Choose how long to practise.",
    missing: "We couldn't find that story. It may have been archived.",
    roleNeeded: "A story can be practised for the role you're set up for. Choose that role, or set this one up first.",
  },
} as const;

/** The areas a focused practice or quick drill can work on. Keys match the API. */
export const practiceFocus = {
  reminderLabel: "What you're practising",
  options: [
    { key: "story", title: "Tell your story", body: "Walk through your background and why this role." },
    { key: "project", title: "Explain a project", body: "Talk through one piece of work from start to finish." },
    { key: "decisions", title: "Explain your decisions", body: "Say why you chose an approach, and what you weighed up." },
    { key: "impact", title: "Show your impact", body: "Describe what changed because of your work." },
    { key: "disagreement", title: "Handle disagreement", body: "Talk about a time you saw things differently from someone." },
    { key: "setback", title: "Learn from what didn't work", body: "Talk honestly about a setback and what came next." },
    { key: "analytics", title: "Think with data", body: "Explain how numbers shaped a decision you made." },
    { key: "role", title: "Role-specific questions", body: "Questions on what this particular role looks for." },
  ],
} as const;

/** The three ways to practise. Never called "modes" or "sessions" on screen. */
export const practiceModes = {
  FULL_INTERVIEW: {
    title: "Full interview",
    body: "A realistic end-to-end interview. Your review comes afterwards.",
    length: "About 20 minutes",
  },
  FOCUSED_PRACTICE: {
    title: "Focused practice",
    body: "Work on one specific area, with a few follow-up questions.",
    length: "4 questions · about 9 minutes",
  },
  QUICK_DRILL: {
    title: "Quick drill",
    body: "Three questions on one area. Short enough to repeat.",
    length: "3 questions · about 5 minutes",
  },
} as Record<string, { title: string; body: string; length: string }>;

/** My Experience: what Mirror draws on when it prepares questions. */
export const experience = {
  eyebrow: "My Experience",
  title: "My Experience",
  intro: "This is what Mirror uses to understand your background and ask more relevant questions.",
  add: "Add something",
  sections: {
    resume: "Resume",
    work: "Work",
    projects: "Projects",
    achievements: "Achievements",
    other: "Other",
  },
  enough: "Mirror has enough information to personalise your practice.",
  addProject: "Adding one recent project will help Mirror ask more specific questions.",
  addResume: "Add your resume so Mirror can prepare questions about your own experience.",
  readingResume: "Mirror is still reading your resume. Your work and projects will appear here once it's done.",
  resumeUnread: "Mirror couldn't finish reading your resume. Your file is saved, and you can replace it or try again.",
  fromResume: "From your resume",
  fromResumeNote: "Work, projects and achievements are read from your resume. Replace your resume to change them.",
  view: "View",
  replace: "Replace",
  viewDetails: "View details",
  present: "Present",
  addProjectAction: "Add a project",
  addAchievementAction: "Add an achievement",
  empty: {
    title: "Your experience is empty.",
    body: "Add a resume, job or project so Mirror can make your practice more relevant.",
    action: "Add experience",
  },
  emptyWork: "No work history has been read from your resume yet.",
  emptyProjects: "No projects yet.",
  emptyAchievements: "No achievements yet.",
  removed: "Recently removed",
  removedBody: "Removed from future practice. Practice you've already finished keeps what it used.",
  restore: "Restore",
  remove: "Remove",
  errors: {
    load: "We couldn't load your experience just now. Your saved files have not been changed.",
  },
} as const;

/** Roles a person is preparing for. */
export const roles = {
  eyebrow: "Roles",
  title: "Roles you're preparing for",
  intro: "Each role shapes the questions Mirror asks and what your review looks at.",
  add: "Prepare for another role",
  active: "Active",
  setupIncomplete: "Setup incomplete",
  notPractisedYet: "Not practised yet",
  continuePreparing: "Continue preparing",
  finishSetup: "Finish setup",
  open: "Open role",
  lastPractised: (day: string) => `Last practised ${day}`,
  empty: {
    title: "You haven't added a role yet.",
    body: "Choose a role you're preparing for to start personalised practice.",
    action: "Add a role",
  },
  errors: {
    load: "We couldn't load your roles just now. Nothing has been removed.",
  },
  detail: {
    back: "All roles",
    start: "Start practice",
    expects: {
      title: "What this role expects",
      body: "Read from the job description you shared for this role.",
      empty: "Mirror is still getting to know this role. Come back in a moment.",
      unreadable: "Mirror couldn't finish getting to know this role. You can prepare it again.",
      themes: "Likely to come up",
      mustHave: "Looked for most",
      niceToHave: "Helpful to have",
    },
    connects: {
      title: "How your experience connects",
      body: "Based on what Mirror has read from your resume.",
      empty: "Add your resume so Mirror can line your experience up with this role.",
      strong: "Strong connection",
      worth: "Worth exploring further",
      notYet: "Not yet demonstrated",
      notYetBody: "Nothing in your experience speaks to this yet.",
    },
    areas: {
      title: "Current preparation areas",
      body: "From your most recent practice for this role.",
      empty: "Complete a practice for this role to see what to work on.",
    },
    history: {
      title: "Practice history",
      empty: "You haven't practised this role yet.",
    },
  },
} as const;

/** Home: what to do now. The server picks the state; these are only the words. */
export const homeNow = {
  preparingFor: "Preparing for:",
  roleLabel: "Role you're preparing for",
  sub: {
    ACTIVE_PRACTICE: "Continue where you left off, or work on what matters next.",
    ACTIVE_PRACTICE_ONLY: "Continue where you left off.",
    REVIEW_PROCESSING: "We're preparing your review. It will be here shortly.",
    REVIEW_FAILED: "Your review didn't finish. Nothing you said is lost.",
    REVIEW_READY: "Your practice is complete. Here's what to do next.",
    FIRST_PRACTICE: "Start your first practice to build your baseline.",
    EARLY_BASELINE: "Your baseline is taking shape.",
    RECOMMENDED_NEXT: (role: string) => `Here's what to focus on next in your ${role} preparation.`,
    RETURNING: (role: string) => `Keep your ${role} preparation moving.`,
    NO_ROLE: "Choose a role to start preparing.",
  },
  active: {
    eyebrow: "Continue where you left off",
    readyEyebrow: "Ready to begin",
    badge: "In progress",
    continue: "Continue practice",
    begin: "Begin practice",
    end: "End this practice",
    question: (number: number, total: number) => `Question ${number} of ${total}`,
    questionsSoFar: (number: number) => (number === 1 ? "1 question so far" : `${number} questions so far`),
    notStarted: "Not started yet",
    lastActive: (when: string) => `Last active ${when}`,
    progressLabel: (number: number, total: number) => `${number} of ${total} questions`,
    endTitle: "End this practice now?",
    endBody: "Your answers so far are kept, and Mirror will prepare your review.",
    endConfirm: "End and prepare my review",
    endCancel: "Keep going",
    ending: "Ending…",
    endFailed: "We couldn't end that practice just now. Nothing was lost.",
  },
  otherRole: {
    eyebrow: "Practice in progress: another role",
    continue: (role: string) => `Continue ${role} practice`,
  },
  upcoming: {
    label: "Interview coming up",
    line: (round: string, role: string, when: string) => `Your ${round ? `${round} ` : ""}interview for ${role} is ${when}.`,
    today: (time: string) => `today at ${time}`,
    tomorrow: (time: string) => `tomorrow at ${time}`,
    later: (day: string, time: string) => `on ${day} at ${time}`,
    readBrief: "Read your brief",
  },
  review: {
    eyebrow: "Your review is ready",
    completed: (count: number | null, when: string) =>
      count ? `Completed ${count} ${count === 1 ? "question" : "questions"} · ${when}` : `Completed ${when}`,
    body: "See what came through clearly and what to work on next.",
    view: "View review",
    processingEyebrow: "Preparing your review",
    processingBody: "This usually takes a minute or two. You can leave this page. It will be here when you come back.",
    failedEyebrow: "Your review didn't finish",
    failedBody: "Your conversation is saved. Mirror can try again without repeating it.",
    retry: "Try again",
    retrying: "Trying again…",
    retryFailed: "We couldn't try again just now. Your conversation is still saved.",
  },
  first: {
    eyebrow: "Let's get started",
    title: (role: string) => `Start your first ${role} practice`,
    body: "We'll use it to establish your first baseline for this role and give you personalised recommendations.",
    cta: (role: string) => `Start ${role} practice`,
  },
  early: {
    eyebrow: "Your first practice",
    title: (role: string) => `Good start on your ${role} preparation.`,
    body: "Your first practice gives Mirror an initial baseline. We'll show clearer trends after a few more practices.",
    cta: "Practise again",
    focusEyebrow: "What to focus on",
    practiceThis: "Practice this",
    seeAnswers: "See your answers",
  },
  recommended: {
    eyebrow: "Recommended next step",
    seeWhy: "See the answers behind this",
    start: (mode: string) => `Start ${mode.toLowerCase()}`,
    title: {
      story: "Practise telling your story",
      project: "Practise explaining a project",
      decisions: "Practise explaining your decisions",
      impact: "Practise showing your impact",
      disagreement: "Practise handling disagreement",
      setback: "Practise learning from what didn't work",
      analytics: "Practise thinking with data",
      role: "Practise role-specific questions",
    } as Record<string, string>,
    titleForTheme: (theme: string) => `Practise ${theme}`,
  },
  returning: {
    eyebrow: "Keep practising",
    title: (role: string) => `Keep building your ${role} practice`,
    body: "Another practice keeps your answers fresh and shows what changes.",
    cta: "Start practice",
  },
  noRole: {
    title: "Choose a role to start preparing.",
    body: "A role gives your practice a clear shape.",
    cta: "Add a role",
  },
  upNext: { eyebrow: "Up next", practiceThis: "Practice this", seeWhy: "See why" },
  since: { eyebrow: "Since your last practice", view: (role: string) => `View ${role} progress` },
  prep: {
    eyebrow: "Your preparation",
    map: {
      title: "Your plan",
      open: "Open your plan",
      ready: (count: number) =>
        count === 0 ? "Every area has an example." : `${count} ${count === 1 ? "area has" : "areas have"} no example yet.`,
      preparing: "Still getting to know this role.",
      unavailable: "We couldn't load this just now.",
    },
    stories: {
      title: "My stories",
      open: "Open stories",
      none: "No stories yet. Add your first example.",
      ready: (count: number) => `${count} ${count === 1 ? "story" : "stories"} ready to use.`,
      developing: (count: number) => `${count} could use more detail.`,
      unavailable: "We couldn't load this just now.",
    },
    progress: {
      title: "Progress",
      open: "View progress",
      start: "Start practising",
      none: (role: string) => `No practices yet for ${role}.`,
      some: (count: number, role: string) => `${count} ${count === 1 ? "practice" : "practices"} recorded for ${role}.`,
    },
  },
  recent: {
    eyebrow: "Recent activity",
    today: "Today",
    review: "Review",
    viewReview: "View review",
    open: "Open",
    continue: "Continue",
    openStory: "Open story",
    storyUpdated: (title: string) => `Updated “${title}” story`,
    all: "View all activity",
    preparing: "Preparing review",
  },
  errors: {
    load: "We couldn't load your Home just now. Nothing you've done has been removed.",
    reload: "Try again",
  },
} as const;

/** Progress: am I getting better? */
export const progress = {
  eyebrow: "Progress",
  title: "Your Progress",
  intro: "See how your interview preparation is developing for each role.",
  addRole: "Add role",
  errors: {
    load: "We couldn't load your progress just now. Nothing you've done has been removed.",
  },
  hub: {
    practices: (count: number) => (count === 1 ? "1 practice" : `${count} practices`),
    lastPractised: (when: string) => `Last practised ${when}`,
    view: "View progress",
    none: "No practice yet",
    noneBody: "Start practising to see your progress and personalised insights for this role.",
    start: "Start practising",
    baseline: "Your baseline is taking shape.",
    positive: { IMPROVING: "Improving", CLEAR: "Coming through clearly" } as Record<string, string>,
    attention: { NEEDS_ATTENTION: "Needs attention", LESS: "Appeared less often" } as Record<string, string>,
    empty: {
      title: "No roles yet.",
      body: "Add a role you're preparing for, and your progress will appear here after your first practice.",
      action: "Add a role",
    },
  },
  role: {
    back: "All roles",
    start: "Start practising",
    tabsLabel: "Sections of this role's progress",
    tabs: { overview: "Overview", answers: "Answers", history: "Practice history", connection: "Role connection" } as Record<string, string>,
    notFound: {
      title: "We couldn't find that role.",
      body: "It may have been removed, or it isn't part of your account.",
    },
  },
  overview: {
    sinceTitle: "Since your last practice",
    sinceOn: (date: string) => `Compared with your previous practice on ${date}.`,
    sinceEarlier: "Compared with your earlier practices for this role.",
    basedOn: (count: number) => `Based on ${count} practices`,
    baselineTitle: "Your baseline is taking shape.",
    baselineBody: "One more practice for this role will show what changed since this one.",
    baselineSeen: "What came through in this practice",
    none: {
      title: "No practice yet",
      body: "Start practising to see your progress and personalised insights for this role.",
    },
    noChange: "Your latest practice covered different ground from the earlier ones, so there is nothing to compare yet.",
  },
  trend: {
    MORE: "Appeared more consistently",
    SIMILAR: "Stayed similar",
    LESS: "Appeared less often",
  } as Record<string, string>,
  insights: {
    role_understanding: {
      MORE: { title: "Role connection appeared more", body: "Your recent answers tied your experience more directly to what this role looks for." },
      SIMILAR: { title: "Role connection stayed similar", body: "Your answers connected to the role about as much as they did before." },
      LESS: { title: "Role connection appeared less often", body: "Some recent answers didn't clearly connect back to what this role requires." },
    },
    examples: {
      MORE: { title: "More specific examples", body: "Your recent answers included clearer details about what you actually did." },
      SIMILAR: { title: "Examples stayed similar", body: "Your examples had about the same level of detail as before." },
      LESS: { title: "Examples were less specific", body: "Some recent answers stayed general instead of describing one situation." },
    },
    depth: {
      MORE: { title: "Decision reasoning appeared more", body: "You explained more of why you chose an approach, not only what you did." },
      SIMILAR: { title: "Decision reasoning stayed similar", body: "The reasoning behind your choices came through about the same as before." },
      LESS: { title: "Decision reasoning appeared less often", body: "Less of the reasoning behind your choices came through this time." },
    },
    impact: {
      MORE: { title: "Impact came through more", body: "You said more about what changed because of your work." },
      SIMILAR: { title: "Impact stayed similar", body: "What changed because of your work came through about the same as before." },
      LESS: { title: "Impact appeared less often", body: "Less of what changed because of your work came through this time." },
    },
  } as Record<string, Record<string, { title: string; body: string }>>,
  timeline: {
    title: "Development over time",
    body: "How consistently these parts appeared in your recent answers.",
    practice: (number: number) => `Practice ${number}`,
    tableLabel: "How each part appeared in each practice",
    legendLabel: "What each marker means",
    areaColumn: "Part of an answer",
    rowLink: (area: string) => `Open ${area}`,
    notEnough: "Not enough information yet",
    scrollHint: "Scroll sideways to see every practice.",
    states: {
      COMING_THROUGH: "Coming through clearly",
      DEVELOPING: "Developing",
      NEEDS_PRACTICE: "Needs practice",
      NOT_EXPLORED: "Not explored yet",
    } as Record<string, string>,
    marker: (number: number, date: string, area: string, state: string) => `Practice ${number}, ${date}, ${area}: ${state}`,
    counts: (strong: number, seen: number) =>
      `Came through clearly in ${strong} of ${seen} ${seen === 1 ? "answer" : "answers"} where this came up.`,
    notExplored: "This didn't come up in this practice. That doesn't count against you. It just hasn't been explored yet.",
    shorter: "This conversation ended early, so it isn't used to compare practices.",
    viewAnswers: "View answers",
    close: "Close",
  },
  definitions: {
    role_understanding: "Do your answers connect your experience to what this role looks for?",
    examples: "Do you describe specific situations, not only general statements?",
    depth: "Do you explain why you chose an approach, not only what you did?",
    impact: "Do you say what changed because of your work?",
  } as Record<string, string>,
  dimension: {
    back: (role: string) => `Back to ${role} progress`,
    unknown: "We couldn't find that part of an answer.",
    recentTitle: "Recent pattern",
    pattern: {
      MORE: "This appears more consistently in recent practices.",
      SIMILAR: "This has stayed similar across recent practices.",
      LESS: "This appears less consistently in recent practices.",
    } as Record<string, string>,
    byState: {
      COMING_THROUGH: "This is coming through clearly.",
      DEVELOPING: "This is still developing.",
      NEEDS_PRACTICE: "This needs more practice.",
      NOT_EXPLORED: "This hasn't come up enough yet to say anything about it. That doesn't count against you.",
    } as Record<string, string>,
    supportingTitle: "Supporting answers",
    supportingBody: "Examples from your recent practices.",
    supportingEmpty: "Mirror didn't tie this to a specific answer yet. It is read from your conversations as a whole.",
    seeAll: "See all answers",
    nextTitle: "What to practise next",
    startFocused: "Start focused practice",
    viewQuestions: "View relevant questions",
    next: {
      role_understanding: "Practise connecting one piece of your experience to what this role needs.",
      examples: "Practise describing one specific situation, with a detail only you would know.",
      depth: "Practise explaining why you chose one approach over another.",
      impact: "Practise finishing your answer with what changed because of your work.",
    } as Record<string, string>,
  },
  answers: {
    title: "Your answers for this part",
    roleTitle: "Your answers",
    body: "Answers where Mirror noticed something about this part.",
    roleBody: "Every answer Mirror noticed something about in your recent practices for this role.",
    filters: { ALL: "All", STRONG: "Strong", NEEDS_PRACTICE: "Needs practice" } as Record<string, string>,
    filterLabel: "Show answers that",
    states: { STRONG: "Came through clearly", PRESENT: "Came up", NEEDS_PRACTICE: "Needs practice" } as Record<string, string>,
    questionOf: (position: number, total: number) => `Question ${position} of ${total}`,
    empty: "No answers to show here yet. This part hasn't been tied to a specific answer.",
    emptyFilter: "None of your recent answers fit this filter.",
    notExplored: (count: number) =>
      `${count} ${count === 1 ? "practice" : "practices"} didn't cover this part. That doesn't count against you.`,
    back: "Back to progress",
  },
  answer: {
    back: (area: string) => `Back to ${area}`,
    yourAnswer: "Your answer",
    noticed: "Mirror noticed",
    noticedEmpty: "Mirror didn't record anything specific about this answer.",
    strengthen: "How to strengthen this",
    tryAgain: "Try again",
    viewConversation: "View full conversation",
    quoteLabel: "From your answer",
    retriesTitle: "Your attempts at this question",
    retriesBody: "Earlier attempts stay as they were. They don't change your progress.",
    attempt: (sequence: number) => `Attempt ${sequence}`,
    unavailable: "We couldn't find that answer. It may not belong to this role.",
  },
  history: {
    title: "Practice history",
    body: "Every finished practice for this role, newest first.",
    empty: "No finished practices for this role yet.",
    questions: (count: number) => `${count} ${count === 1 ? "question" : "questions"}`,
    shorter: "Ended early",
    open: "Open review",
  },
  connection: {
    title: "Role connection",
    body: "What does this role expect you to demonstrate, and where has it appeared in your answers?",
    seen: { REPEATEDLY: "Seen repeatedly", SOMETIMES: "Seen sometimes", NOT_EXPLORED: "Not explored yet" } as Record<string, string>,
    note: "Not explored yet doesn't count against you. It only means it hasn't come up in your answers.",
    preparing: "Mirror is still getting to know this role. Role connection will appear when that's done.",
    unavailable: "Mirror couldn't read what this role expects, so there is nothing to connect yet.",
    noPractice: "Practise this role to see where its expectations come up in your answers.",
    practices: (count: number) => (count === 1 ? "In 1 practice" : `In ${count} practices`),
    viewAnswers: "View answers",
    answersFor: (area: string) => `Answers that spoke to ${area}`,
    showAnswers: "Show answers",
    hideAnswers: "Hide answers",
    empty: "This hasn't come up in your answers yet.",
  },
  meanings: {
    role_understanding: {
      means: "Interviewers want to see that you understand what the role involves, and that your experience speaks to it.",
      steps: [
        "What the role is responsible for",
        "Which part of your experience matches it",
        "What you'd want to learn quickly",
      ],
    },
    examples: {
      means: "Interviewers remember specific situations far more than general statements.",
      steps: [
        "The situation, in one or two sentences",
        "What you did in it",
        "One detail only you would know",
      ],
    },
    depth: {
      means: "Interviewers often want to understand how you think, not only what you did.",
      steps: [
        "Explain why you chose this approach over other options",
        "Connect the decision to the situation you were in",
        "Show your reasoning, not just the outcome",
      ],
    },
    impact: {
      means: "Interviewers often want to understand what changed because of your work.",
      steps: [
        "What situation existed",
        "What you changed",
        "What happened afterwards",
      ],
    },
  } as Record<string, { means: string; steps: readonly string[] }>,
} as const;

/** The full review of one practice. */
export const review = {
  eyebrow: "Review",
  back: "Practice",
  overview: "Overview",
  clearTitle: "What came through clearly",
  clearEmpty: "This conversation was a little short, so there isn't a clear pattern to point to yet.",
  improveTitle: "What needs more work",
  toImprove: (count: number) => `${count} to work on`,
  nextChoose: "Choose something you'd like to practise.",
  nextChooseAction: "Choose a practice",
  improveEmpty: "Your review didn't point to one area to work on next.",
  improveFrom: "From",
  answersTitle: "Your answers",
  answersBody: "Everything you were asked, in the order it came up.",
  answersEmpty: "Your conversation isn't available to read back just now.",
  answersUnavailable: "We couldn't bring back your conversation just now. The rest of your review is still here.",
  question: "Question",
  yourAnswer: "Your answer",
  noAnswer: "You moved on without answering this one.",
  cameThrough: "What came through",
  couldBeClearer: "What could be clearer",
  nothingNoted: "Nothing specific was noted for this answer.",
  nextTitle: "Your next practice",
  nextStart: "Start",
  nextMinutes: "About 8 minutes",
  practiceThis: "Practice this",
  readiness: "Where you stand",
  readinessNote: "These appear as ranges because one conversation can only show so much.",
} as const;

/** Settings: predictable, and nothing hidden here that belongs elsewhere. */
export const settings = {
  eyebrow: "Settings",
  title: "Settings",
  intro: "Your details, your practice preferences and the information Mirror has saved.",
  profile: {
    title: "Profile",
    body: "This name appears in your space. Your email is managed by the account you sign in with.",
    name: "Full name",
    email: "Email address",
    save: "Save changes",
    saving: "Saving…",
    saved: "Your profile has been updated.",
  },
  interview: {
    title: "Interview preferences",
    body: "How your practice conversations run.",
    language: "Language you'd like to practice in",
    languageNote: "Mirror speaks with you in this language where it can.",
    mode: "How you answer",
    modeValue: "Speaking, with typing available at any point",
    modeNote: "You can switch to typing during a conversation whenever you prefer.",
    saved: "Your preferences have been saved.",
  },
  privacy: {
    title: "Privacy and data",
    body: "What Mirror has saved, and where to manage it.",
    experience: "Your experience",
    experienceBody: "The resumes, projects and other work Mirror draws on.",
    history: "Your practice history",
    historyBody: "Every conversation you've had and the review that followed.",
    note: "Your resume and conversations stay private to you, and are not intentionally used to train third-party models.",
    deletion: "Removing your account",
    deletionBody: "Mirror can't remove your whole account from here yet. Write to us and we'll take care of it and confirm when it's done.",
    deletionAction: "Email us about removing your account",
  },
  notifications: {
    title: "Notifications",
    body: "Mirror doesn't send notifications yet. When your review is ready it appears on your Home page, and your conversation is always saved.",
  },
  account: {
    title: "Account",
    body: "Your sign-in is managed by the account you signed up with.",
    signOut: "Sign out",
    signingOut: "Signing out…",
  },
  errors: {
    load: "We couldn't load your settings just now. Please try again.",
    save: "We couldn't save that just now. Please try again.",
  },
} as const;

/** Help: short, because the product should explain itself. */
export const help = {
  eyebrow: "Help",
  title: "How Mirror works",
  intro: "Mirror helps you practise talking about your own experience, then shows you what came through.",
  contactLabel: "Still stuck?",
  contact: "Write to us and a person will read it.",
  contactAction: "Email support",
  sections: [
    {
      title: "How Mirror works",
      body: "You add your experience, choose a role, and have a friendly conversation. Afterwards Mirror puts together a review of what came through clearly and what to work on next.",
    },
    {
      title: "Preparing for an interview",
      body: "Add a role with its job description. Mirror reads the role and your experience together, then prepares questions about your own work rather than generic ones.",
    },
    {
      title: "Understanding your review",
      body: "Your review starts with what came through clearly, then up to three things to work on. If a conversation was short, some areas will say not explored yet. That's a normal outcome, not a problem.",
    },
    {
      title: "Managing your information",
      body: "My Experience holds everything Mirror draws on. You can add, replace and remove items at any time. Practice you've already finished keeps the version it used.",
    },
    {
      title: "Privacy",
      body: "Your resume and conversations stay private to you, and are not intentionally used to train third-party models. Mirror is a practice partner, not a hiring decision-maker.",
    },
  ],
} as const;

/** The menu behind the avatar. Not a second copy of the main navigation. */
export const profileMenu = {
  open: "Your account",
  close: "Close menu",
  profile: "Profile",
  preferences: "Interview preferences",
  account: "Account settings",
  help: "Help and support",
  signOut: "Sign out",
  signOutFailed: "We couldn't sign you out just now. Please try again.",
} as const;

/** Interview Map: what a role is likely to explore, next to what you can already show. */
export const interviewMap = {
  eyebrow: "Interview Map",
  title: "What this interview is likely to explore",
  intro: "Taken from the role and your own experience. These are likely themes, not a list of questions you will definitely get.",
  inferred: "You didn't add a job description for this role, so these themes are typical for the role rather than taken from a specific job.",
  fromJob: "From the job description",
  themesTitle: "Likely interview themes",
  strengthsTitle: "You already have useful experience for",
  strengthsEmpty: "We haven't found experience that clearly matches these themes yet.",
  practiseStory: "Practise this story",
  areasTitle: "Prepare these areas",
  areasEmpty: "Nothing stands out as missing for this role right now. Practice will show what still needs work.",
  questionsTitle: "Questions worth preparing for",
  questionsNote: "Questions like these often come up for this kind of role. Preparing an answer helps whether or not you're asked exactly this.",
  alsoExpected: "The role also mentions",
  coverage: {
    PREPARED: "Story ready",
    EXPERIENCE: "Useful experience",
    MENTIONED: "Mentioned, not yet shown",
    MISSING: "No example yet",
  } as Record<string, string>,
  matchKinds: {
    STORY: "Your story",
    WORK: "Your work",
    PROJECT: "Your project",
    ACHIEVEMENT: "Your achievement",
    SKILL: "Named on your resume",
    TOOL: "Named on your resume",
  } as Record<string, string>,
  actions: {
    FIND_STORY: "Help me find a story",
    PRESSURE_TEST: "Dig deeper into your resume",
    PRACTICE: "Practice this",
    ADD_EXPERIENCE: "Add your experience",
  } as Record<string, string>,
  states: {
    preparing: "Mirror is still getting to know this role. This page will fill in once it's done.",
    unreadable: "Mirror couldn't finish reading this role. You can prepare it again from Roles.",
    reading: "Mirror is still reading your resume, so your side of the map is empty for now.",
    unreadableResume: "Mirror couldn't read your resume, so your side of the map is empty. Replacing it in My Experience usually fixes this.",
  },
  errors: {
    load: "We couldn't load your interview map just now. Nothing has been removed.",
  },
  pressureCta: "Dig deeper",
  pressureBody: "Find more to say before you practise saying it out loud.",
} as const;

/** The parts of one role's preparation workspace. */
export const roleWorkspace = {
  label: "Role preparation",
  map: "Interview Map",
  pressure: "Dig Deeper",
  interviews: "Interviews",
} as const;

/** Dig Deeper (internally the resume pressure test): see where an interviewer may ask you to explain more. */
export const pressureTest = {
  eyebrow: "Dig Deeper",
  title: "Dig deeper into your resume",
  intro: "See where an interviewer may ask you to explain more. Statements most relevant to this role come first.",
  mayAsk: "An interviewer may ask",
  howReady: "How prepared are you to explain this?",
  canExplain: "I can explain this",
  needPrepare: "I need to prepare",
  marked: { CAN_EXPLAIN: "You said you can explain this", NEEDS_PREPARATION: "Marked to prepare" } as Record<string, string>,
  start: "Dig deeper",
  relatedTo: "Relevant to",
  where: "From your resume",
  question: (step: number, total: number) => `Question ${step} of ${total}`,
  answerLabel: "Your answer",
  answerHint: "Answer in your own words, as you would out loud. Mirror only uses what you write.",
  check: "Check my answer",
  checking: "Checking…",
  noticed: "What we noticed",
  tryFollowUp: "A follow-up you might hear",
  next: "Next question",
  finish: "Finish",
  stop: "Stop here",
  saveStory: "Save my answers as a story",
  saving: "Saving…",
  savedStory: "Open your story",
  checksNote: "These notes only say what's in your answer. They're not a grade.",
  states: {
    NO_RESUME: "Add your resume in My Experience so Mirror can find the statements worth preparing.",
    READING: "Mirror is still reading your resume. Come back in a moment.",
    UNREADABLE: "Mirror couldn't read statements from your resume. Replacing it in My Experience usually fixes this.",
  } as Record<string, string>,
  errors: {
    load: "We couldn't load your resume statements just now. Nothing has been removed.",
    save: "We couldn't save that just now. Please try again.",
    check: "We couldn't check that answer just now. Your answer is still here.",
  },
} as const;

/** My Stories: how you explain a real experience in an interview. */
export const stories = {
  eyebrow: "My Stories",
  title: "My Stories",
  intro: "Your experience is what happened. A story is how you explain it in an interview. Build a few you can tell clearly and reuse.",
  add: "Add a story",
  findOne: "Help me find a story",
  empty: {
    title: "You haven't written a story yet.",
    body: "Start from something on your resume, or let Mirror help you find an example for an area you still need to prepare.",
  },
  from: {
    MANUAL: "Written by you",
    PRESSURE_TEST: "From Dig Deeper",
    FIND_A_STORY: "Found with Mirror's help",
    EXPERIENCE: "From your experience",
  } as Record<string, string>,
  completeness: {
    READY: "Ready to tell",
    DEVELOPING: "Developing",
    STARTED: "Needs more detail",
  } as Record<string, string>,
  /** One state and one next action per story, shown in My Stories and on the story page. */
  state: {
    addDetail: "Add detail",
    readyToPractise: "Ready to practise",
    practised: "Practised",
    suggested: "Improvement suggested",
    continueStory: "Continue story",
    practiseAgain: "Practise again",
  },
  groups: {
    context: "Context",
    whatYouDid: "What you did",
    whatChanged: "What changed",
    reflection: "Reflection",
  },
  nextPart: (label: string) => `Add next: ${label.toLowerCase()}`,
  sourceLabel: "Based on",
  themesLabel: "Themes",
  themesHint: "Separate themes with commas, for example: stakeholder management, pricing. Use the same wording as an area on your Interview Map so this story counts as preparation for it.",
  titleLabel: "Story title",
  titleHint: "A short name you'll recognise, for example “Rebuilding the pricing model”.",
  save: "Save story",
  saving: "Saving…",
  saved: "Your story is saved.",
  open: "Open",
  archive: "Archive story",
  archiveTitle: "Archive this story?",
  archiveBody: "It moves out of your active stories and stops counting toward your Interview Map. Its versions and anything that points to it are kept. You can restore it later.",
  cancel: "Cancel",
  confirmArchive: "Archive story",
  archived: {
    title: "Archived stories",
    body: "These don't count toward your Interview Map. Restore one to use it again.",
    on: (day: string) => `Archived ${day}`,
    notice: "This story is archived. It doesn't count toward your Interview Map, and it can't be edited until you restore it.",
    restore: "Restore story",
    restoring: "Restoring…",
    restored: "Your story is active again.",
  },
  roles: {
    title: "Useful for",
    intro: "One story can work for several roles. Its own themes count toward every role's Interview Map. Add a role to show where you'd use it, with extra themes and what to bring forward for that role only. The story itself stays the same.",
    acrossRoles: "Useful across roles",
    usefulFor: (names: string) => `Useful for ${names}`,
    none: "Not linked to a role yet. Its own themes still count toward every role's Interview Map.",
    add: "Add a role",
    choose: "Role",
    themesLabel: "Themes for this role",
    themesHint: "Areas on this role's Interview Map this story helps with, on top of the story's own themes. Separate them with commas.",
    emphasisLabel: "Emphasize for this role",
    emphasisHint: "Optional. A short note on which part of the story to lead with for this role.",
    emphasisShown: (text: string) => `Emphasize: ${text}`,
    noExtraThemes: "Uses the story's own themes",
    edit: "Edit",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    remove: "Remove",
    removing: "Removing…",
    added: (name: string) => `This story is now useful for ${name}.`,
    saved: "Saved.",
    removed: (name: string) => `Removed from ${name}. The story itself hasn't changed.`,
    allLinked: "This story is already linked to every role you're preparing for.",
    noRoles: "Add a target role first, then you can position this story for it.",
    archived: "Restore the story to change its roles.",
    addedOn: (label: string, day: string) => `${label} (added ${day})`,
    unknown: "A role you no longer have",
    reuse: "Already written this story for another role? Open it in My Stories and add this role to it instead of writing it again.",
    reuseLink: "Go to My Stories",
  },
  practice: {
    title: "Practice history",
    intro: "Each time you practise this story, it's listed here with the version you practised. Editing or archiving the story keeps this history.",
    none: "You haven't practised this story yet.",
    start: "Practise this story",
    archivedNote: "Restore the story to practise it again.",
    times: (count: number) => (count === 1 ? "Practised once" : `Practised ${count} times`),
    last: (day: string) => `last ${day}`,
    never: "Not practised yet",
    row: (day: string, mode: string) => `${day} · ${mode}`,
    version: (n: number) => `Version ${n}`,
    notStarted: "Set up, not started",
    started: "Practised",
    review: "Open review",
  },
  suggestions: {
    title: "Suggested improvements",
    intro: "From your reviews. Each one is about the version you practised. You decide what, if anything, to change.",
    reviewTitle: "Improve this story",
    reviewIntro: "Your review noticed something about how one of your stories came across. Nothing changes unless you edit the story.",
    issue: {
      OWNERSHIP_UNCLEAR: {
        title: "What you personally did didn't come through clearly",
        why: "Interviewers want to know which part was yours. Add what you decided, did or changed yourself.",
      },
      RESULT_UNSUPPORTED: {
        title: "The size of the result wasn't backed up",
        why: "A number is only convincing if you can say where it came from. Add how you measured it, or say it's an estimate.",
      },
    } as Record<string, { title: string; why: string }>,
    part: (label: string) => `Belongs in: ${label}`,
    practised: (n: number, day: string) => `From your practice on ${day}, using version ${n}`,
    olderVersion: (practised: number, current: number) =>
      `This is about version ${practised}, the one you practised. Your story is now version ${current}, so check whether it still applies.`,
    improve: "Improve story",
    dismiss: "Dismiss",
    dismissing: "Dismissing…",
    archived: "This story is archived. Restore it before improving it.",
    none: "No suggestions from your reviews.",
    earlier: (count: number) => `Earlier suggestions (${count})`,
    accepted: (n: number | null) => (n ? `Improved in version ${n}` : "Improved"),
    dismissed: "Dismissed",
    count: (count: number) => (count === 1 ? "1 improvement to review" : `${count} improvements to review`),
    banner: "From your review",
    bannerNote: "You control this edit. Nothing is saved until you choose Save story.",
    acceptedNotice: "Saved. This suggestion is marked as done.",
    stillOpen: "Saved. The suggestion stays open until you change the part it's about.",
  },
  history: {
    title: "Version history",
    disclosure: "See earlier versions",
    intro: "Each time you save a change, the earlier version is kept here. Earlier versions can be viewed but not edited.",
    onlyOne: "There's one version so far.",
    version: (n: number) => `Version ${n}`,
    current: "Current version",
    earlier: "Earlier version",
    view: "View",
    hide: "Close",
    reason: {
      CREATED: (day: string) => `Created ${day}`,
      MANUAL_EDIT: (day: string) => `Updated ${day}`,
      RESTORED: (day: string, from: number | null) => (from ? `Restored from version ${from} on ${day}` : `Restored from an earlier version on ${day}`),
    },
    readOnly: "You're viewing an earlier version. It can't be edited.",
    empty: "Not written in this version.",
    restore: "Make this the current version",
    restoring: "Bringing it back…",
    restoreNote: "Your current version stays in history. This one is added as a new version.",
    saveFirst: "Save or undo your unsaved changes first.",
    archivedFirst: "Restore the story first to bring back an earlier version.",
    restored: (n: number) => `Version ${n} is your current version again.`,
  },
  back: "My Stories",
  parts: {
    situation: { label: "Situation", prompt: "What was going on, and why did it matter?" },
    ownership: { label: "What you owned", prompt: "Which part was yours, as opposed to the team's?" },
    actions: { label: "What you did", prompt: "The steps you took, in your own words." },
    reasoning: { label: "Why you chose that approach", prompt: "What options did you have, and why this one?" },
    trade_offs: { label: "Trade-offs", prompt: "What did you give up, or what was the risk?" },
    outcome: { label: "Outcome", prompt: "What happened afterwards?" },
    measurable_result: { label: "Measurable result", prompt: "How big was the change? A range or an estimate is fine, if you say so." },
    learning: { label: "What you learned", prompt: "What would you take into your next role?" },
    do_differently: { label: "What you'd do differently", prompt: "Looking back, what would you change?" },
  } as Record<string, { label: string; prompt: string }>,
  guide: {
    eyebrow: "Help me find a story",
    title: (theme: string) => `Find a story about ${theme.toLowerCase()}`,
    titleGeneral: "Find a story from your own experience",
    intro: "Mirror asks, you answer. Only what you write goes into the story, and you can stop at any point.",
    step: (step: number, total: number) => `Step ${step} of ${total}`,
    next: "Next",
    back: "Back",
    finish: "Save my story",
    nothingYet: "Nothing comes to mind? That's useful to know. Try a different project, a class, or work outside a job.",
    prompts: [
      { part: "situation", prompt: (theme: string) => `Think about a time ${theme.toLowerCase()} really mattered in your work, study or a project. What was going on?` },
      { part: "ownership", prompt: () => "What was your part in it, as opposed to other people's?" },
      { part: "actions", prompt: () => "What did you actually do? Walk through the steps." },
      { part: "reasoning", prompt: () => "Why did you approach it that way? Was there another option?" },
      { part: "outcome", prompt: () => "What happened in the end? Include anything you can measure, and say if it's an estimate." },
    ],
  },
  errors: {
    load: "We couldn't load your stories just now. Nothing has been removed.",
    save: "We couldn't save your story just now. Your writing is still here.",
    archive: "We couldn't archive that story just now. It's still in your stories.",
    restore: "We couldn't restore that story just now. Please try again.",
    history: "We couldn't load this story's versions just now.",
    restoreVersion: "We couldn't bring back that version just now. Your current version is unchanged.",
    roles: "We couldn't load this story's roles just now.",
    roleSave: "We couldn't save that just now. Nothing has changed.",
    roleRemove: "We couldn't remove that role just now. Nothing has changed.",
    practice: "We couldn't load this story's practice history just now.",
    suggestions: "We couldn't load suggestions just now.",
    dismiss: "We couldn't dismiss that just now. Please try again.",
  },
} as const;

/** Try again: answer the same question again and see what is different. */
export const tryAgain = {
  action: "Try again",
  again: "Try once more",
  done: "Continue",
  question: "The question",
  yourFirst: "Your first answer",
  yourLatest: "Your latest answer",
  answerLabel: "Your new answer",
  answerHint: "Answer the same question again, in your own words. Your first answer is kept exactly as it was.",
  submit: "Compare with my first answer",
  comparing: "Comparing your answers…",
  whatChanged: "What changed",
  stillWorth: "Still worth adding",
  nothingChanged: "Your two answers cover much the same ground.",
  nothingMissing: "Nothing obvious is missing from this answer.",
  firstAttempt: "First attempt",
  latestAttempt: "Latest attempt",
  cameThrough: "Came through",
  stillUnclear: "Still unclear",
  suggestion: "For next time",
  latestAvailable: (count: number) => (count === 1 ? "You've tried this once more" : `You've tried this ${count} more times`),
  showComparison: "Compare your answers",
  hideComparison: "Hide comparison",
  checksNote: "These notes only say what is in each answer. They're not a grade.",
  errors: {
    save: "We couldn't save that attempt just now. Your answer is still here.",
    notFinished: "You can try again once this practice has finished.",
  },
  gained: {
    SITUATION: "The situation is clearer",
    OWNERSHIP: "Your role is clearer",
    ACTIONS: "What you did is clearer",
    REASONING: "You explained why you chose that approach",
    RESULT: "You said what happened afterwards",
    MEASURE: "You gave a sense of how big the change was",
    SPECIFIC_EXAMPLE: "It's about one real situation",
  } as Record<string, string>,
  missing: {
    SITUATION: "What was going on",
    OWNERSHIP: "Your own contribution",
    ACTIONS: "The steps you took",
    REASONING: "Why you chose that approach",
    RESULT: "What happened afterwards",
    MEASURE: "How big the change was",
    SPECIFIC_EXAMPLE: "One specific situation",
  } as Record<string, string>,
  aspect: {
    SITUATION: "situation",
    OWNERSHIP: "your contribution",
    ACTIONS: "what you did",
    REASONING: "reasoning",
    RESULT: "result",
    MEASURE: "size of the result",
    SPECIFIC_EXAMPLE: "a specific example",
  } as Record<string, string>,
} as const;

/** Real interviews for one role: a night-before brief, then how it went. */
export const interviews = {
  eyebrow: "Interviews",
  title: "Your interviews",
  intro: "Add an interview you have booked for this role. You'll get a short brief built from your own material, and a place to note how it went.",
  upcoming: "Coming up",
  past: "Already happened",
  empty: {
    title: "No interviews added yet",
    body: "When you have an interview booked for this role, add it here.",
  },
  add: {
    title: "Add an interview",
    when: "Date and time",
    round: "Round",
    company: "Company (optional)",
    companyHint: "Only a label for you. Mirror doesn't look anything up.",
    submit: "Add interview",
    saving: "Adding…",
    added: "Interview added.",
  },
  edit: {
    open: "Edit details",
    title: "Edit details",
    submit: "Save details",
    saving: "Saving…",
    cancel: "Cancel",
    saved: "Details saved.",
  },
  rounds: {
    SCREENING: "Screening",
    TECHNICAL: "Technical",
    BEHAVIOURAL: "Behavioural",
    HR: "HR",
    OTHER: "Other",
  } as Record<string, string>,
  timing: {
    UPCOMING: "Coming up",
    SOON: "Within two days",
    PAST: "Already happened",
  } as Record<string, string>,
  open: "Open brief",
  debriefPrompt: "Note how it went",
  debriefDone: "How it went is saved",
  remove: "Remove",
  removeConfirm: "Remove this interview and anything you noted about it?",
  back: "All interviews",
  brief: {
    title: (round: string) => `${round} interview`,
    intro: "A short brief for the night before, built from this role and your own material.",
    themesTitle: "Questions worth preparing for",
    themesNote: "Questions like these often come up for this kind of role. They are a way to get ready, not a list of what will happen.",
    support: "What you have",
    openStory: "Open story",
    recheckTitle: "Statements to go over again",
    recheckNote: "Parts of your resume an interviewer may ask you to explain.",
    recheckOpen: "Go to Dig Deeper",
    recheckQuestion: "An interviewer may ask",
    focusTitle: "From your latest practice",
    openReview: "Open review",
    askTitle: "Questions you could ask them",
    limitsTitle: "What this brief is built from",
    states: {
      ROLE_PREPARING: "We're still reading this role. The brief will fill in once that's done.",
      ROLE_UNREADABLE: "We couldn't read this role's brief, so there's nothing to build from yet.",
    } as Record<string, string>,
  },
  debrief: {
    title: "How it went",
    intro: "Only you know what happened. Note it while it's fresh; it helps you prepare for what comes next.",
    earlyNote: "This interview hasn't happened yet. You can still note things now.",
    questions: "Questions they asked",
    questionsHint: "One per line. Up to 15.",
    feeling: "How did it feel?",
    feelingNone: "Rather not say",
    feelings: {
      WENT_WELL: "It went well",
      MIXED: "Mixed",
      WENT_BADLY: "It didn't go well",
    } as Record<string, string>,
    outcome: "Where things stand",
    outcomes: {
      WAITING: "Waiting to hear",
      NEXT_ROUND: "Moved to the next round",
      OFFER: "Offer",
      NOT_SELECTED: "Not selected",
      WITHDREW: "I withdrew",
    } as Record<string, string>,
    notes: "Notes (optional)",
    save: "Save how it went",
    saving: "Saving…",
    saved: "Saved.",
    followUpsTitle: "What to prepare next",
    followUpsNote: "Each question you noted, matched to this role's themes. This is about what to prepare, not about why things went the way they did.",
    noTheme: "Not linked to a theme for this role",
    actions: {
      ADD_STORY: "Add a story",
      STRENGTHEN_STORY: "Strengthen this story",
    } as Record<string, string>,
  },
  errors: {
    load: "We couldn't load your interviews just now.",
    loadBrief: "We couldn't load this brief just now.",
    add: "We couldn't add that interview. Check the date and try again.",
    remove: "We couldn't remove that interview just now.",
    save: "We couldn't save that just now. Your notes are still here.",
    edit: "We couldn't save those details. Check the date and try again.",
  },
} as const;
